workflows:
  android-workflow:
    name: Android Workflow

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab